      Subroutine Type2201
!-----------------------------------------------------------------------------------------------------------------------
! DESCRIPTION: Calculate the temperature of the liquid leaving the ice tank as well as the ice inventory level given the
!  temperature and flow rate of the liquid entering the tank and the ice inventory at the beginning of the timestep.
!  Also takes the operating mode (charge, discharge, bypass) as input.

! Object: Thermal Storage
! Simulation Studio Model: Thermal Storage
! 

! Author: Greg Johnson
! Editor: Amanda Pertzborn
! Date:	 November 09, 2021
! last modified: March 21, 2024
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			C1				parameter learned from data [-Inf;+Inf]
!			C2				parameter learned from data [-Inf;+Inf]
!			C3				parameter learned from data [-Inf;+Inf]
!			C4				parameter learned from data [-Inf;+Inf]
!			C5				parameter learned from data [-Inf;+Inf]
!			C6				parameter learned from data [-Inf;+Inf]
!			CR_Chiller1		charge rate of Chiller1 [kJ/hr] [0,+Inf]
!			CR_Chiller2		charge rate of Chiller2 [kJ/hr] [0,+Inf]
!			Cp				specific heat of the liquid [kJ/kg-K] [0,+Inf]
!			tol				tolerance used when solving for the outlet temperature[-Inf;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			T_in			temperature of the liquid entering the ice tank [C] [-Inf;+Inf]
!			m_dot			mass flow rate of the liquid through the ice tank [kg/hr] [-Inf;+Inf]
!			iceinvs			current ice inventory level [-] [-Inf;+Inf]
!			pmode			operating mode of ice tank; 1 and 2 = discharge; 3 = charge; 4 = bypass [-] [1,4]
!			smode			determinies which chiller is used for charging [-] [1,2]

! *** 
! *** Model Outputs 
! *** 
!			T_out			temperature of the liquid leaving the ice tank [C] [-Inf;+Inf]
!			flow_out		mass flow rate of the liquid through the ice tank [kg/hr] [-Inf;+Inf]
!			iceinve			ice inventory at the end of the time step [-] [0;+1]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type2201

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep, Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      DOUBLE PRECISION C1
      DOUBLE PRECISION C2
      DOUBLE PRECISION C3
      DOUBLE PRECISION C4
      DOUBLE PRECISION C5
      DOUBLE PRECISION C6
      DOUBLE PRECISION CR_Chiller1
      DOUBLE PRECISION CR_Chiller2
      DOUBLE PRECISION Cp
      DOUBLE PRECISION tol

!    INPUTS
      DOUBLE PRECISION T_in, T_out
      DOUBLE PRECISION m
      DOUBLE PRECISION iceinvs, iceinve
      DOUBLE PRECISION pmode
      DOUBLE PRECISION smode

!    VARIABLES
      DOUBLE PRECISION a , b , c
      DOUBLE PRECISION fa , fb , fc
      DOUBLE PRECISION a0, a1, a2, error, its,n,tempa,tempb
      DOUBLE PRECISION debug1, debug2, debug3, debug4

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(10)           !The number of parameters that the the model wants
		Call SetNumberofInputs(5)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(8) !3                !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      C1 = getParameterValue(1)
      C2 = getParameterValue(2)
      C3 = getParameterValue(3)
      C4 = getParameterValue(4)
      C5 = getParameterValue(5)
      C6 = getParameterValue(6)
      CR_Chiller1 = getParameterValue(7)
      CR_Chiller2 = getParameterValue(8)
      Cp = getParameterValue(9)
      tol = getParameterValue(10)


      T_in = GetInputValue(1)
      m = GetInputValue(2) ! converted to kg/s in the equations
      iceinvs = GetInputValue(3)
      pmode = GetInputValue(4)
      smode = GetInputValue(5)


   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0) ! T_out
		Call SetOutputValue(2, m) ! flow_out
		Call SetOutputValue(3, iceinvs) ! iceinve
		! These values are used for troubleshooting
        Call SetOutputValue(4, 0) ! a0
		Call SetOutputValue(5, 0) ! a1
		Call SetOutputValue(6, 0) ! a2
        Call SetOutputValue(7, 0) ! y0
		Call SetOutputValue(8, 0) ! y1

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      C1 = getParameterValue(1)
      C2 = getParameterValue(2)
      C3 = getParameterValue(3)
      C4 = getParameterValue(4)
      C5 = getParameterValue(5)
      C6 = getParameterValue(6)
      CR_Chiller1 = getParameterValue(7)
      CR_Chiller2 = getParameterValue(8)
      Cp = getParameterValue(9)
      tol = getParameterValue(10)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      T_in = GetInputValue(1)
      m = GetInputValue(2)
      iceinvs = GetInputValue(3)
      pmode = GetInputValue(4)
      smode = GetInputValue(5)
		

      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------
    ! 334 [kJ/kg] is latent heat of fusion and 2846 [kg] is ice mass; could be added as parameters
    ! timestep = 60 s
    ! m = m/3600 ! kg/hr to kg/s
    a0 = Cp*(timestep*3600)/(334*2846.35)   
    a1 = C1 + (C2*(1 - iceinvs)) + (C3*(1 - iceinvs)*(1 - iceinvs))
    a2 = C4 + (C5*(1 - iceinvs)) + (C6*(1 - iceinvs)*(1 - iceinvs))
    
	! If no ice, bypass
    if (m == 0) then
        pmode = 4
    endif    
	
    If ((pmode == 1).OR.(pmode == 2)) Then
		! Discharge mode
        a = 0.1
        b = T_in-0.1
        debug1 = log(T_in/a)
        debug2 = log(T_in/b)
        fa = real(dble(a1+a2*(T_in-a)/max(0.0001,log(T_in/a)/10)))-(m/3600.d0)*a0*(T_in-a)
        fb = real(dble(a1+a2*(T_in-b)/max(0.0001,log(T_in/b)/10)))-(m/3600.d0)*a0*(T_in-b)

        !fa = real(dble(a1-(m/3600.d0)*a0*(T_in-a)))
        if (abs(fa)>abs(b)) then
            tempa = a
            tempb = b
            a = tempb
            b = tempa
            tempa = fa
            tempb = fb
            fa = tempb
            fb = tempa
        endif

        its = 0
        n = 1000
        c = 1
        
        do while ((abs(c) > tol).AND.(its<n))
            if ( abs(fa)>abs(fb) ) then
                tempa = a 
                tempb = b
                a = tempb
                b = tempa
                tempa = fa
                tempb = fb
                fa = tempb
                fb = tempa
            endif
            
            if (fa /= fb) then
                c = (b-a)/(fb-fa)            
                b = a
                fb = fa
                c = c*fa
                a = max(a-c,0.1)
                debug3 = log(T_in/a)
                debug4 = log(T_in/b)
                fa = real(dble(a1+a2*(T_in-a)/log(T_in/a)/10))-(m/3600.d0)*a0*(T_in-a)            
                its = its + 1
            else
                c = 0
                its = n
            endif
                
        end do
             
        error = c
        T_out = REAL(dble(a))
        iceinve = iceinvs - ((Cp*(m/3600.d0)*(timestep*3600.d0)*(-T_out + T_in)) / (334*2846.35))     !This line could also use an explanation of where these denominator numbers come from. I will have to look through the documentation
        if (iceinve < 0) Then
            iceinve = 0
        endif
        if (fa /= fa) then
            fa = 0
        endif
        Call SetOutputValue(4, a0)
        Call SetOutputValue(5, a1)
        Call SetOutputValue(6, a2)
        Call SetOutputValue(7, 0) ! fa
        Call SetOutputValue(8,0)   ! fb
        
    
    Else If ((pmode == 3) .AND. (smode == 1)) Then
		! Charge mode, using Chiller1
        T_out = CR_Chiller1 /(Cp*(m/3600)) + T_in        
        iceinve = iceinvs - ((Cp*(m/3600)*(3600*timestep)*(-T_out + T_in)) / (334*2846.35) )
        If (iceinve > 1) Then
            iceinve = 1
        Endif
        
        
    Else If ((pmode == 3) .AND. (smode == 2)) Then
		! Charge mode, using Chiller2
        T_out = CR_Chiller2 /(Cp*(m/3600)) + T_in
        iceinve = iceinvs - ((Cp*(m/3600)*(3600*timestep)*(-T_out + T_in)) / (334*2846.35) )
        if (iceinve > 1) Then
            iceinve = 1
        Endif
        
        
    Else If (pmode == 4) Then
		! Bypass mode
        T_out = T_in
        iceinve = iceinvs
        
    Endif    
    
    
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
!-----------------------------------------------------------------------------------------------------------------------
        
        Call SetOutputValue(1, T_out) ! T_out
		Call SetOutputValue(2, m) ! flow_out
		Call SetOutputValue(3, iceinve) ! iceinve
        
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

