      Subroutine Type9318
!-----------------------------------------------------------------------------------------------------------------------
! DESCRIPTION: Given damper positions, fan speeds, and some airflows, 
! calculate the pressures, airflow rates, and fan power consumption.
! Object: Air System Control
! Simulation Studio Model: Airflow Calculation
! 

! Author: Adam Kopach, modified by Amanda Pertzborn
! Editor: Adam Kopach
! Date:	 May 26, 2020
! last modified: March 20, 2024
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Upstream_Pressure		upstream pressure	[inH2O] [-Inf;+Inf]
!			Downstream_Pressure		downstream pressure	[inH2O] [-Inf;+Inf]
! 			xfit(1..10)			    10 parameters for fan power calculation [-] [-Inf,+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Fan_Speed				fan speed	[rpm] [0;+Inf]
!			D(1) 					damper 1 position	[%] [-Inf;+Inf]
!			D(2)					damper 2 position	[%] [-Inf;+Inf]
!			D(3)					VAV damper position	[%] [-Inf;+Inf]
!			D(4)					VAV damper position	[%] [-Inf;+Inf]
!			D(5)					damper 5 position	[%] [-Inf;+Inf]
!			F1 						ventilation airflow rate at AHU (i.e., outdoor air) [cfm] [0,+Inf]
!			F5 						flow rate in VAV [cfm] [0,+Inf]
!			F7 						flow rate in VAV [cfm] [0,+Inf]

! *** 
! *** Model Outputs 
! *** 
!			F1 						ventilation airflow rate at AHU (i.e., outdoor air) [cfm] [0,+Inf]
!			F2						flow rate at position 2 [cfm] [0,+Inf]
!			F3						flow rate at position 3 [cfm] [0,+Inf]
!			F4						flow rate at position 4 [cfm] [0,+Inf]
!			F5 						flow rate in VAV [cfm] [0,+Inf]
!			F6						flow rate at position 6 [cfm] [0,+Inf]
!			F7 						flow rate in VAV [cfm] [0,+Inf]
!			F8						flow rate at position 8 [cfm] [0,+Inf]
!			F9						flow rate at position 9 [cfm] [0,+Inf]
!			F10						flow rate at position 10 [cfm] [0,+Inf]
!			F11						flow rate at position 11 [cfm] [0,+Inf]
!			F12						flow rate at position 12 [cfm] [0,+Inf]
!			F13						flow rate at position 13 [cfm] [0,+Inf]
!			P1 						pressure at position 1 [inH2O] [-Inf,+Inf]
!			P2						pressure at position 2 [inH2O] [-Inf,+Inf]
!			P3						pressure at position 3 [inH2O] [-Inf,+Inf]
!			P4						pressure at position 4 [inH2O] [-Inf,+Inf]
!			P5 						pressure at position 5 [inH2O] [-Inf,+Inf]
!			P6						pressure at position 6 [inH2O] [-Inf,+Inf]
!			P7 						pressure at position 7 [inH2O] [-Inf,+Inf]
!			P8						pressure at position 8 [inH2O] [-Inf,+Inf]
!			P9						pressure at position 9 [inH2O] [-Inf,+Inf]
!			P10						pressure at position 10 [inH2O] [-Inf,+Inf]
!			P11						pressure at position 11 [inH2O] [-Inf,+Inf]
!			P12						pressure at position 12 [inH2O] [-Inf,+Inf]
!			P13						pressure at position 13 [inH2O] [-Inf,+Inf]
!			Fan_Speed				fan speed [rpm] [0,+Inf]
!			Fan_Power				fan power [W] [0,+Inf]
! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type9318

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType
      Double Precision Airflow
      Double Precision Damper,err1,err2,err3   
   
!    PARAMETERS
      DOUBLE PRECISION Upstream_Pressure
      DOUBLE PRECISION Downstream_Pressure,xfit(10)

!    INPUTS
      DOUBLE PRECISION Fan_Speed,F1,F5,F7
      Double Precision D(5)

!     OUTPUTS
      DOUBLE PRECISION Fan_Power
	  Double Precision P(13),F(13)  
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(12)           !The number of parameters that the the model wants
		Call SetNumberofInputs(9)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(28)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
	  ! Parameters
      Upstream_Pressure = getParameterValue(1)
      Downstream_Pressure = getParameterValue(2)
      xfit(1) = getParameterValue(3)
      xfit(2) = getParameterValue(4)
      xfit(3) = getParameterValue(5)
      xfit(4) = getParameterValue(6)
      xfit(5) = getParameterValue(7)
      xfit(6) = getParameterValue(8)
      xfit(7) = getParameterValue(9)
      xfit(8) = getParameterValue(10)
      xfit(9) = getParameterValue(11)
      xfit(10) = getParameterValue(12)
	  ! Inputs
      Fan_Speed = GetInputValue(1)
      D(1) = GetInputValue(2)
      D(2) = GetInputValue(3)
      D(3) = GetInputValue(4)
      D(4) = GetInputValue(5)
      D(5) = GetInputValue(6)
      F1 = GetInputValue(7)
      F5 = GetInputValue(8)
	  F7 = GetInputValue(9)
      
      F = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)
      P = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)

   !Set the Initial Values of the Outputs (#,Value)
    Call SetOutputValue(1, 0.d0) ! Outlet Air flow
    Call SetOutputValue(2, 0.d0) ! Outlet Air flow
    Call SetOutputValue(3, 0.d0) ! Outlet Air flow
    Call SetOutputValue(4, 0.d0) ! Outlet Air flow
    Call SetOutputValue(5, 0.d0) ! Outlet Air flow
    Call SetOutputValue(6, 0.d0) ! Outlet Air flow
    Call SetOutputValue(7, 0.d0) ! Outlet Air flow
    Call SetOutputValue(8, 0.d0) ! Outlet Air flow
    Call SetOutputValue(9, 0.d0) ! Outlet Air flow
    Call SetOutputValue(10, 0.d0) ! Outlet Air flow
    Call SetOutputValue(11, 0.d0) ! Outlet Air flow
    Call SetOutputValue(12, 0.d0) ! Outlet Air flow
    Call SetOutputValue(13, 0.d0) ! Outlet Air flow
    Call SetOutputValue(14, 0.d0) ! Outlet Air flow
    Call SetOutputValue(15, 0.d0) ! Outlet Air flow
    Call SetOutputValue(16, 0.d0) ! Outlet Air flow
    Call SetOutputValue(17, 0.d0) ! Outlet Air flow
    Call SetOutputValue(18, 0.d0) ! Outlet Air flow
    Call SetOutputValue(19, 0.d0) ! Outlet Air flow
    Call SetOutputValue(20, 0.d0) ! Outlet Air flow
    Call SetOutputValue(21, 0.d0) ! Outlet Air flow
    Call SetOutputValue(22, 0.d0) ! Outlet Air flow
    Call SetOutputValue(23, 0.d0) ! Outlet Air flow
    Call SetOutputValue(24, 0.d0) ! Outlet Air flow
    Call SetOutputValue(25, 0.d0) ! Outlet Air flow
    Call SetOutputValue(26, 0.d0) ! Outlet Air flow
    Call SetOutputValue(27, 0.d0) ! Outlet Air flow
    Call SetOutputValue(28, 0.d0) ! fan Power

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Upstream_Pressure = getParameterValue(1)
      Downstream_Pressure = getParameterValue(2)
		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      Fan_Speed = GetInputValue(1)
      D(1) = GetInputValue(2)
      D(2) = GetInputValue(3)
      D(3) = GetInputValue(4)
      D(4) = GetInputValue(5)
      D(5) = GetInputValue(6)
	  F1 = GetInputValue(7)
      F5 = GetInputValue(8)
	  F7 = GetInputValue(9)	
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

    Call PF(Upstream_Pressure,Downstream_Pressure,D,Fan_Speed,F1,F5,F7,P,F)
    Call FanPower(xfit,Fan_speed,F5,F7,Fan_Power)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
    Call SetOutputValue(1, F(1)) ! Outlet Air flow
    Call SetOutputValue(2, F(2)) ! Outlet Air flow
    Call SetOutputValue(3, F(3)) ! Outlet Air flow
    Call SetOutputValue(4, F(4)) ! Outlet Air flow
    Call SetOutputValue(5, F(5)) ! Outlet Air flow
    Call SetOutputValue(6, F(6)) ! Outlet Air flow
    Call SetOutputValue(7, F(7)) ! Outlet Air flow
    Call SetOutputValue(8, F(8)) ! Outlet Air flow
    Call SetOutputValue(9, F(9)) ! Outlet Air flow
    Call SetOutputValue(10, F(10)) ! Outlet Air flow
    Call SetOutputValue(11, F(11)) ! Outlet Air flow
    Call SetOutputValue(12, F(12)) ! Outlet Air flow
    Call SetOutputValue(13, F(13)) ! Outlet Air flow
    Call SetOutputValue(14, P(1)) ! Outlet Air flow
    Call SetOutputValue(15, P(2)) ! Outlet Air flow
    Call SetOutputValue(16, P(3)) ! Outlet Air flow
    Call SetOutputValue(17, P(4)) ! Outlet Air flow
    Call SetOutputValue(18, P(5)) ! Outlet Air flow
    Call SetOutputValue(19, P(6)) ! Outlet Air flow
    Call SetOutputValue(20, P(7)) ! Outlet Air flow
    Call SetOutputValue(21, P(8)) ! Outlet Air flow
    Call SetOutputValue(22, P(9)) ! Outlet Air flow
    Call SetOutputValue(23, P(10)) ! Outlet Air flow
    Call SetOutputValue(24, P(11)) ! Outlet Air flow
    Call SetOutputValue(25, P(12)) ! Outlet Air flow
    Call SetOutputValue(26, P(13)) ! Outlet Air flow
    Call SetOutputValue(27, Fan_Speed) ! Outlet Air flow
    Call SetOutputValue(28, Fan_Power) ! Outlet Air flow
    

      Return
      End
!-----------------------------------------------------------------------------------------------------------------------
Subroutine FanPressure(Fan,Flow,Pressure)
Implicit None
DOuble Precision Fan, Flow, Pressure
    Double Precision Maximum_Airflow_Fan
    Double Precision Maximum_Pressure_Fan
    Double Precision Airflow_Ratio_Fan
    Double Precision Static_Pressure_Ratio_Fan
    Double Precision Fan_Pressure, x(12)
    ! Estimate pressure head of the fan
	
    ! AHU1 and AHU2 parameter values
    x(1) = -44.54911319
    x(2) = 1.229626021
    x(3) = -3.82E-05
    x(4) = 2.05E-09
    x(5) = -0.354686394
    x(6) = 0.000356361
    x(7) = 3.33E-07
    x(8) = -1.96E-11
    x(9) = 0.972310705
    x(10) = 3.532383436
    x(11) = 2.648306318
    x(12) = -8.881447363
    
    Maximum_Airflow_Fan = x(1) + x(2)*Fan + x(3)*Fan*Fan + x(4)*Fan*Fan*Fan
    Maximum_Pressure_Fan = x(5) + x(6)*Fan + x(7)*Fan*Fan + x(8)*Fan*Fan*Fan       
    Airflow_Ratio_Fan = Flow/Maximum_Airflow_Fan
    Static_Pressure_Ratio_Fan = x(9) + x(10)*Airflow_Ratio_Fan + x(11)*Airflow_Ratio_Fan*Airflow_Ratio_Fan + x(12)*Airflow_Ratio_Fan*Airflow_Ratio_Fan*Airflow_Ratio_Fan   
    Pressure = Maximum_Pressure_Fan*Static_Pressure_Ratio_Fan
    return
    end
    
Subroutine DamperPressure(Damper,Flow,Pressure)
Implicit None
    Double Precision Damper,Flow,Pressure
    Double Precision Maximum_Airflow_Damper
    Double Precision Maximum_Pressure_Damper
    Double Precision Airflow_Ratio_Damper
    Double Precision Static_Pressure_Ratio_Damper
    Double Precision Damper_Pressure, x(11)    
	! Estimate pressure drop at the damper
	
    ! Parameter values
    x(1) = 0.47756113
    x(2) = -0.05875562
    x(3) = 0.002586923
    x(4) = -3.05E-05
    x(5) = 176.4703098
    x(6) = -3.099063723
    x(7) = 0.267506011
    x(8) = 0.000242882
    x(9) = 0.056306909
    x(10) = 0.177969601
    x(11) = -0.007260614

    Maximum_Pressure_Damper = x(1) + x(2)*Damper + x(3)*Damper*Damper + x(4)*Damper*Damper*Damper
    Maximum_Airflow_Damper = x(5) + x(6)*Damper + x(7)*Damper*Damper + x(8)*Damper*Damper*Damper
    Airflow_Ratio_Damper = Flow/Maximum_Airflow_Damper
    Static_Pressure_Ratio_Damper = x(9)*Airflow_Ratio_Damper + x(10)*Airflow_Ratio_Damper*Airflow_Ratio_Damper + x(11)*Airflow_Ratio_Damper*Airflow_Ratio_Damper*Airflow_Ratio_Damper
    Pressure = Static_Pressure_Ratio_Damper*Maximum_Pressure_Damper
    return
    end 
   
 
 Subroutine PFin(P_in,P_out,D,N,F1,F5,F7,P,F)
 Implicit None
 Double Precision P_in, P_out, D(5),N,F11,F(13),P(13),P_calc,frac,err2,err3
 double precision F5,F7,F1
 F = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)
 P = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)
 
 F(1) = F1
 F(5) = F5
 F(7) = F7

 F(2) = F(1)
 F(3) = F(5) + F(7)
 F(4) = F(3)
 F(6) = F(5)
 F(8) = F(7)
 F(9) = F(5) + F(7)
 F(11) = F(3) - F(2)
 F(10) = F(11)
 F(12) = F(9) - F(10)
 F(13) = F(12)
 
 P(1) = P_in
 Call DamperPressure(D(1),F(1),P_calc)
 P(2) = P(1) - P_calc
 P(3) = P(2)
 Call FanPressure(N,F(3),P_calc)
 P(4) = P(3) + P_calc
 P(5) = P(4)
 P(7) = P(4)
 Call DamperPressure(D(3),F(5),P_calc)
 P(6) = P(5) - P_calc
 Call DamperPressure(D(4),F(7),P_calc)
 P(8) = P(7) - P_calc
 P(9)=P(6)
 P(10)=P(9)
 P(12)=P(9)
 Call DamperPressure(D(5),F(12),P_calc)
 P(13) = P(12) - P_calc
 Call DamperPressure(D(2),F(11),P_calc)
 P(11) = P(10) - P_calc
 
 return 
 end
 
 Subroutine PF3(P_in,P_out,D,N,F1,F5,F7,P,F)
 Implicit None
 double precision P_in,P_out,D,N,F11,err2,err3,F1,P(13),F(13),done, dF1,F1_low, F1_high,err2_high,err2_low
 double precision F5,F7
 integer itn
 F = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)
 P = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)
 Call PFin(P_in,P_out,D,N,F1,F5,F7,P,F) 
 
 return 
 end
 
 Subroutine PF(P_in,P_out,D,N,F1,F5,F7,P,F)
 Implicit None
 double precision P_in,P_out,D,N,F1,F11,P(13),F(13),done,dF11,F11_low,F11_high,err3_low,err3_high,err3
 double precision F5,F7
 integer itn
 ! Calculate pressures and flows
 ! initialize flow and pressure arrays
  F = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)
  P = (/0,0,0,0,0,0,0,0,0,0,0,0,0/)

 Call PF3(P_in,P_out,D,N,F1,F5,F7,P,F)

 return
 end
 
 Subroutine FanPower(xfit,N,F5,F7,Fan_Power)
 Implicit None
 double precision xfit(10),N,F5,F7,Q,Fan_Power
 ! Flow rates in cfm
 ! fan speed in rpm
 ! Created from a fit to data in MATLAB
 Q = F5 + F7
 Fan_Power = xfit(1)+xfit(2)*N+xfit(3)*Q+xfit(4)*N*N+xfit(5)*N*Q+xfit(6)*Q*Q+ &
             xfit(7)*N*N*N+xfit(8)*N*N*Q+xfit(9)*N*Q*Q+xfit(10)*Q*Q*Q
 
 return
 end
 
 
