      Subroutine Type9106
!-----------------------------------------------------------------------------------------------------------------------
! DESCRIPTION: Calculate the rotational speed of Pump3, the secondary loop pump, given the differential pressure and the 
!	differential pressure setpoint
! Object: Pump Control (Adam Kopach)
! Simulation Studio Model: Pump Controller
! 

! Author: Adam Kopach
! Editor: Amanda Pertzborn
! Date:	 August 20, 2020
! last modified: March 21, 2024
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Max_Operating_RPM		max operating [rpm]	[0,+Inf]
!			Min_Operating_RPM		min operating [rpm]	[0,+Inf]
!			dfdt_max				maximum rate of change of setpoint pressure [psi/s] [-Inf;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			P13						pressure at location 13 (upstream pressure) [psi] [-Inf;+Inf]
!			P19						pressure at location 19 (downstream pressure) [psi] [-Inf;+Inf]
!			Pump_Speed_in			current pump speed [rpm] [0,+Inf]
!			Setpoint_Pressure		setpoint pressure for pump [psi]
!			enable					signal that determines if the pump is being used
! *** 
! *** Model Outputs 
! *** 
!			Pump_Speed			    pump speed	[rpm] [-Inf;+Inf]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type9106

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      DOUBLE PRECISION Max_Operating_RPM
      DOUBLE PRECISION Min_Operating_RPM
      DOUBLE PRECISION Setpoint_Pressure
      Double Precision dfdt_max

!    INPUTS
      DOUBLE PRECISION P19,P13,DP_SL
      DOUBLE PRECISION Pump_Speed,Pump_Speed_in,diff,dfdt
      Double precision enable

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(3)           !The number of parameters that the the model wants
		Call SetNumberofInputs(5)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(1)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(1)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,1)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Max_Operating_RPM = getParameterValue(1)
      Min_Operating_RPM = getParameterValue(2)
      dfdt_max = getParameterValue(3)

      P13 = GetInputValue(1)
      P19 = GetInputValue(2)
      Pump_Speed_in = GetInputValue(3)
      Setpoint_Pressure = GetInputValue(4)
      enable = GetInputValue(5)
      Pump_Speed_in = GetNumericalSolution(1)

   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, Pump_Speed) ! Fan Speed
        Call SetDynamicArrayValueThisIteration(1,Pump_Speed_in)


		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Max_Operating_RPM = getParameterValue(1)
      Min_Operating_RPM = getParameterValue(2)
      dfdt_max = getParameterValue(3)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      P13 = GetInputValue(1)
      P19 = GetInputValue(2)
      Pump_Speed_in = GetInputValue(3)
      Setpoint_Pressure = GetInputValue(4)
      enable = GetInputValue(5)

      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------
    if (enable < 1) then
		! Pump is not operating
        Min_Operating_RPM = 0   
        Pump_Speed = Min_Operating_RPM
    else    
        Pump_Speed_in = getDynamicArrayValueLastTimestep(1) ! pump speed from prior step
        DP_SL = P13-P19 ! differential pressure (DP) across SL
        diff = DP_SL-Setpoint_Pressure ! error in the DP (value minus setpoint)
        dfdt = 0
		! The larger the DP is relative to the sP, the larger the change in speed
		! If the difference is positive, decrease speed; if negative, increase speed
        If (diff >= 1) Then
            dfdt = -dfdt_max 
        ElseIf ((diff > .5)) Then
            dfdt = -0.75*dfdt_max
        ElseIf ((diff > .25)) Then
             dfdt = -0.50*dfdt_max
        ElseIf ((diff > .15)) Then
            dfdt = -0.25*dfdt_max
        ElseIf (diff <= -1) Then
            dfdt = dfdt_max
        ElseIf ((diff < -.5)) Then
            dfdt = 0.75*dfdt_max
        ElseIf ((diff < -.25)) Then
            dfdt = 0.50*dfdt_max
        ElseIf ((diff < -.15)) Then
            dfdt = 0.25*dfdt_max
        EndIf

		! Calculate the new pump speed based on the DP error
        Pump_Speed = Pump_Speed_in + dfdt*Timestep*3600

		! Limit the pump speed between the min and max
        If (Pump_Speed < Min_Operating_RPM) Then
            Pump_Speed = Min_Operating_RPM
        ElseIf (Pump_Speed > Max_Operating_RPM) Then
            Pump_Speed = Max_Operating_RPM
        EndIf    
    endif
    Call setDynamicArrayValueThisIteration(1,Pump_Speed)
    
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
		Call SetOutputValue(1, Pump_Speed) ! Fan Speed

 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

